name: openfunds
services:
  # Backend Service
  server:
    build:
      context: ./server
      target: production
    restart: unless-stopped
    networks:
      mcvlan:
        ipv4_address: 192.168.15.17
    environment:
      NODE_ENV: production
      PORT: 5050
      ATLAS_URI: ${ATLAS_URI}
      JWT_SECRET: ${JWT_SECRET}
      MAILTRAP_TOKEN: ${MAILTRAP_TOKEN}
      # Backend CORS: The NAS IP/Domain
      CORS_ORIGIN: "https://ipartin.com"
    volumes:
      # Fix: Added absolute path on NAS
      # - server-uploads:/app/uploads
      - /volume1/@docker/volumes/openfunds_server-uploads/_data:/app/uploads

  # Frontend Build Service (Purpose: just to build assets)
  client_build:
    build:
      context: ./client
      target: build_stage
      args:
        - VITE_API_BASE_URL=/api
    volumes:
      - client-dist:/app/dist # Mount a volume to capture the 'dist' output

  # Frontend Serving Service (Purpose: serve static files for the external Nginx)
  client:
    image: nginx:alpine # Or another lightweight web server image
    restart: unless-stopped
    networks:
      mcvlan:
        ipv4_address: 192.168.15.18
    volumes:
      # Mount the 'dist' folder generated by the client_build service
      - client-dist:/usr/share/nginx/html:ro # Read-only mount of the built client assets
    depends_on:
      - client_build # Ensure client_build completes before client starts
      - server # Client needs the server to be available for initial API calls

networks:
  mcvlan:
    external: true
    ipam:
      config:
        - subnet: 192.168.15.0/24
          gateway: 192.168.15.1

volumes:
  # Fix: Commented out the previous volume definition
  # server-uploads:
  client-dist: # Define the named volume for client build temporary output