name: openfunds-dev
services:
  server:
    build:
      context: ./server
      target: development
    restart: unless-stopped
    # Excluded for portainerenv_file: ./server/config.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5050:5050"
    networks:
      - openfunds-dev-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    build:
      context: ./client
      target: development
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - openfunds-dev-network
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - server

networks:
    openfunds-dev-network:
      driver: bridge