name: openfunds
services:
  # Backend Service
  server:
    build:
      context: ./server
      target: production
    restart: unless-stopped
    networks:
      - openfunds-network
    environment:
      NODE_ENV: production
      PORT: 5050
      ATLAS_URI: ${ATLAS_URI}
      JWT_SECRET: ${JWT_SECRET}
      MAILTRAP_TOKEN: ${MAILTRAP_TOKEN}
      # Backend CORS: The NAS IP/Domain
      CORS_ORIGIN: "http://192.168.15.13,http://dsm1.ipartin.com"
    volumes:
      - server-uploads:/app/uploads

  # Frontend Build Service (Purpose: just to build assets)
  client_build:
    build:
      context: ./client
      target: build_stage
      args:
        - VITE_API_BASE_URL=/api
    volumes:
      - client-dist:/app/dist # Mount a volume to capture the 'dist' output

  # Nginx Reverse Proxy and Static File Server
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80" # Map host port 80 to Nginx's port 80
      - "443:443" # For HTTPS (if you configure SSL in nginx.conf)
    networks:
      - openfunds-network
    volumes:
      # Mount the Nginx configuration file from your host
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount the 'dist' folder generated by the client_build service
      - client-dist:/usr/share/nginx/html:ro # Mount the built client assets
    depends_on:
      - server
      - client_build

networks:
    openfunds-network:
      driver: bridge

volumes:
  server-uploads:
  client-dist: # Define the named volume for client build output