import mongoose from "mongoose";

const recordSchema = new mongoose.Schema({
  ofid: {
    type: String,
    required: true,
    unique: true,
  },
  fieldName: {
    type: String,
    required: true,
  },
  dataType: {
    type: String,
  },
  description: {
    type: String,
  },
  values: {
    type: String,
  },
  level: {
    type: String,
  },
  tags: [
    {
      type: String,
      enum: [
        "Additional",
        "Alternative Fund",
        "AT",
        " AT",
        "AT ",
        "Attribute",
        "AU",
        "BE",
        " BE",
        "BE ",
        " BE ",
        "CEPT",
        "CH",
        "CL",
        "Classification",
        "Codes",
        "Companies",
        "Comprehensive enumeration",
        "Contact Information",
        "Core",
        "Corporate actions reporting",
        "Country-AT",
        "Country specific field",
        "DCPT",
        "DE",
        "Distribution data and corporate actions",
        "DK",
        "DOR",
        "Dynamic Data",
        "EET",
        "EFT",
        "EMT",
        "EMT 2.0",
        "EPT",
        "ES",
        "ESG",
        "Essential",
        "ETF",
        "Execution data",
        "Fees and expenses",
        "Field to ignore (during transmission)",
        "FR",
        "Full",
        "FVPT",
        "GB",
        "General information",
        "HK",
        "Hybrid Field",
        "Hybrid Field ",
        " Hybrid Field",
        " Hybrid Field ",
        "IE",
        "Internal",
        "IT",
        "Key Fact: Company",
        "Key Fact: Fund",
        "Key Fact: Fund Manager",
        "Key Fact: Listing",
        "Key Fact: Share Class",
        "Key Fact: Umbrella",
        "KR",
        "KR ",
        "Legal structure",
        "LI",
        "LU",
        "many",
        "MiFID II data",
        "MiFID II target market",
        "Multiple country field (XX=ISO country code)",
        " Multiple country field (XX=ISO country code)",
        "Multiple country field (XX=ISO country code) ",
        " Multiple country field (XX=ISO country code) ",
        " News",
        "News ",
        "News",
        "NL",
        "NL ",
        "No longer supported",
        "Non-openfunds field (use senders field name instead)",
        "NZ",
        " NZ",
        "NZ ",
        "People",
        "Performance and risk data",
        "Portfolio Holdings",
        " Portfolio Manager",
        "Portfolio Manager ",
        "Portfolio Manager",
        "Prices, assets and number of shares",
        "PRIIP data",
        "PRIIPs and MiFID cost fields",
        "Purchase information",
        "Ratios and Exposures ",
        "Ratios and Exposures",
        "Removed",
        "RG97",
        "SG",
        "Solvency II",
        "Tax data",
        "Taxes",
        "Test Tags",
        "TPT",
        " TPT ",
        "US",
      ],
      required: false,
    },
  ],
  example: {
    type: String,
  },
  linkReference: {
    type: String,
  },
  introduced: {
    type: Number,
    required: true,
  },
  deprecated: {
    type: Number,
  },
  uploadedFile: {
    type: String,
  },
});

export default mongoose.model("Record", recordSchema);
